ALTER TABLE IF EXISTS recipes ADD COLUMN pos_6 int DEFAULT NULL;
ALTER TABLE IF EXISTS recipes ADD COLUMN pos_11 int DEFAULT NULL;
ALTER TABLE IF EXISTS recipes ADD CONSTRAINT recipes_pos_6_fkey FOREIGN KEY(pos_6) REFERENCES tips_and_tubes(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE IF EXISTS recipes ADD CONSTRAINT recipes_pos_11_fkey FOREIGN KEY(pos_11) REFERENCES tips_and_tubes(id) ON DELETE SET NULL ON UPDATE CASCADE;
