dyes:
  - name: "FAM"
    position: 2
    targets: ["HIV","COVID"]
  - name: "CY5"
    position: 1
    targets: ["DENGUE","HBV"]
  - name: "VIC"
    position: 3
    targets: ["HCV"]
  - name: "NED"
    position: 4
    targets: ["COVID"]
  - name: "ROX"
    position: 6
    targets: ["CANCER"]
  - name: "SYBR"
    position: 5
    targets: ["TB"]

ic_position: 6         # IC: internal Control Position

activeWells: [1,2,3,4,7,32,88,92,93,94,95,96]

redlowerlimit: 5
redupperlimit: 25
orangelowerlimit: 25