Cartridge:
  - id: 1
    labwareID: 1
    type: "extraction"
    description: "Extraction Cartridge"
    wellNum: 1
    distance: 17.5
    height: 2
    volume: 10
  - id: 2
    labwareID: 1
    type: "extraction"
    description: "Extraction Cartridge"
    wellNum: 2
    distance: 24.5
    height: 2
    volume: 10
  - id: 3
    labwareID: 1
    type: "extraction"
    description: "Extraction Cartridge"
    wellNum: 3
    distance: 33.3
    height: 2
    volume: 10
  - id: 4
    labwareID: 1
    type: "extraction"
    description: "Extraction Cartridge"
    wellNum: 4
    distance: 41.20
    height: 2
    volume: 10
  - id: 5
    labwareID: 1
    type: "extraction"
    description: "Extraction Cartridge"
    wellNum: 5
    distance: 51.10
    height: 2
    volume: 10
  - id: 6
    labwareID: 1
    type: "extraction"
    description: "Extraction Cartridge"
    wellNum: 6
    distance: 62.99
    height: 2
    volume: 10
  - id: 7
    labwareID: 1
    type: "extraction"
    description: "Extraction Cartridge"
    wellNum: 7
    distance: 74.90
    height: 2
    volume: 10
  - id: 8
    labwareID: 1
    type: "extraction"
    description: "Extraction Cartridge"
    wellNum: 8
    distance: 84.3
    height: 2
    volume: 10
  - id: 9
    labwareID: 1
    type: "pcr"
    description: "PCR Cartridge"
    wellNum: 1
    distance: 5
    height: 2
    volume: 10
  - id: 10
    labwareID: 1
    type: "pcr"
    description: "PCR Cartridge"
    wellNum: 2
    distance: 11.9
    height: 2
    volume: 10
  - id: 11
    labwareID: 1
    type: "pcr"
    description: "PCR Cartridge"
    wellNum: 3
    distance: 18.8
    height: 2
    volume: 10
  - id: 12
    labwareID: 1
    type: "pcr"
    description: "PCR Cartridge"
    wellNum: 4
    distance: 25.70
    height: 2
    volume: 10
