TipsTubes:
  - id : 1
    name : 'extraction_tip_1000ul'
    type: 'tip'
    allowedPositions: [1,2,3]
    volume: 1000
    height: 98
  
  - id : 2
    name : 'pcr_tip_1000ul'
    type: 'tip'
    allowedPositions: [1,2,3]
    volume: 1000
    height: 98
  
  - id : 3
    name : 'piercing_tip'
    type: 'tip'
    allowedPositions: [4,5]
    volume: 0.00
    height: 39
  
  - id : 4
    name : 'sample_tube'
    type: 'tube'
    allowedPositions: [6]
    volume: 1500
    height: 43.70
  
  - id : 5
    name : 'shaker_tube'
    type: 'tube'
    allowedPositions: [7]
    volume: 5000
    height: 58.88
  
  - id : 6
    name : 'extraction_collection_tube'
    type: 'tube'
    allowedPositions: [9]
    volume: 1500
    height: 43.70
  
  - id : 7
    name : 'pcr_collection_tube'
    type: 'tube'
    allowedPositions: [11]
    volume: 200
    height: 15.80
